### ISSUE TITLE
Trace logging

### ISSUE THREAD

**Issue by Ciesix** [Ciesix/Walter#1]
The trace logger should record information about a program's execution to a file. All log entries should contain; An incremented number, timestamp, process id, trace level, source (class and method), message / exception.

**Requirements**
- Files should be tagged with the project name and date `<Name>.<YYYY-MM-DD>.log`.
- Writing messages to file, should be done async.

**Tasks**
- [ ] Start logging with information about the current version.
- [ ] Stop logging.
- [ ] Log trace messages using Verbose, Information, Warning and Error methods.
- [ ] Log files older then a month, should be deleted.
